[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
include_trailing_comma = true

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = true
pretty = true
strict = true
follow_imports = "normal"
exclude = "^tests/"
files = ["src", "packages/automation"]

[[tool.mypy.overrides]]
module = [
    "macro_system.*",
    "meta_agent.*",
    "qa_engine.*",
    "packages.automation.macro_system.*",
    "packages.automation.meta_agent.*",
    "packages.automation.qa_engine.*",
]
ignore_errors = true

[[tool.mypy.overrides]]
module = [
    "scripts.*",
    "src.cursor.cursor_client",
    "src.cursor.cursor_client.*",
    "src.mobile.*",
]
ignore_errors = true

[tool.pytest.ini_options]
addopts = "-ra --showlocals"
testpaths = [
    "tests",
    "packages/automation/meta_agent/tests",
    "packages/automation/macro_system/tests",
]

[tool.bandit]
targets = ["macro_system", "meta_agent", "qa"]
exclude_dirs = ["tests"]
skips = ["B101"]
