# Example configuration for Google News Drive Sync.
# Populate this file with real API keys and credentials in your local environment only.

news_api:
  api_key: 'YOUR_NEWS_API_KEY'
  base_url: 'https://newsapi.org/v2/top-headlines'
  topics:
    - technology
    - science
  language: en
  country: us
  page_size: 20
  max_articles: 50

sources:
  rss:
    - 'https://hnrss.org/frontpage'
  rss_limit_per_feed: 10

document:
  format: markdown
  timezone: UTC

drive:
  folder_name: 'Shared News Feed'
  oauth_credentials_path: 'credentials.json'
  token_storage_path: '../cache/drive_token.enc'

scheduler:
  enabled: true
  update_interval_minutes: 180
  timezone: UTC
  cron: null

cache:
  path: '../cache/articles.db'
  retention_days: 14

repository:
  enabled: true
  path: '../cache/articles.db'

plugins:
  enabled: false
  packages:
    - 'src.plugins.sample_plugin'
  paths: []
  settings:
    sample:
      enabled: false
  sandbox:
    enabled: true
    timeout_seconds: 30
    max_workers: 4

server:
  host: '127.0.0.1'
  port: 8000
  auth:
    api_keys:
      - 'REPLACE_WITH_SECURE_KEY'
  rate_limit:
    requests_per_minute: 120
    window_seconds: 60

secrets:
  env_file: '../.env'
  encryption_key_env: 'TOKEN_ENCRYPTION_KEY'
