privacy:
  enable_pii_scrubbing: true
  allowed_pii_patterns: []
  blocked_pii_patterns:
    - email
    - phone
    - ssn
monitoring:
  drift_detection_window: 500
  alert_threshold: 0.2
  latency_budget_ms: 200
fairness:
  enforce: true
  sensitive_attributes:
    - gender
    - age_group
  min_samples_per_group: 20
compliance:
  audit_log_dir: ./results/audit
  model_card_dir: ./docs/model_cards
