name: Enforce AGENTS.md Standards

on:
  pull_request:
    branches: [main]

jobs:
  codex-rules-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Locate AGENTS instructions manifest
        id: resolve-agents
        run: |
          set -euo pipefail

          if [ -f AGENTS.md ]; then
            path="AGENTS.md"
          else
            path="$(find . -maxdepth 2 -type f -name AGENTS.md | head -n1 || true)"
          fi

          if [ -z "$path" ]; then
            echo "❌ AGENTS instructions missing!" >&2
            exit 1
          fi

          clean_path="${path#./}"
          echo "path=$clean_path" >>"$GITHUB_OUTPUT"
          echo "AGENTS_FILE=$clean_path" >>"$GITHUB_ENV"

      - name: Validate AGENTS.md content
        run: |
          set -euo pipefail
          grep -q "## Codex Instructions" "$AGENTS_FILE" || echo "⚠️ No Codex section found."

      - name: Display AGENTS.md summary
        run: |
          echo "----- AGENTS.md HEADERS -----"
          if ! grep '^##' "$AGENTS_FILE"; then
            echo "No headers found"
          fi
