---
name: PR Security Gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          deny-licenses: 'GPL-1.0,GPL-2.0,GPL-3.0,AGPL-1.0,AGPL-3.0'
          fail-on-severity: high

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog scan
        uses: trufflesecurity/trufflehog@v3.81.7
        with:
          extra_args: >-
            filesystem
            --only-verified
            --fail
            .

  semgrep-incremental:
    name: Incremental SAST
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Semgrep diff scan
        uses: semgrep/semgrep-action@v1
        with:
          config: p/security-audit
          baseline-ref: origin/${{ github.event.pull_request.base.ref }}
          generateSarif: true
          sarif: semgrep.sarif

      - name: Upload Semgrep results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
